### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by XavRsl** [LaravelDaily/Laravel-Auth-Invitations#1]
Thanks for the great work! This fits my use case just on time when I needed it.

The only thing that you could have done in order to make others save it would have been to commit the laravel core as a first commit, then your changes as a second one. That way it would have been easier to spot all the files that have been changed in the process.

Thanks!

**Comment by PovilasKorop** [comment]
Thanks for the tip, it doesn't fit the workflow with demo projects, we experiment a lot before doing any public commit. But will keep in mind!
