### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by rndmendes** [LaravelDaily/Laravel-Auth-Invitations#5]
Illuminate\Contracts\Container\BindingResolutionException
Target class [HasInvitation] does not exist.

**Comment by PovilasKorop** [comment]
@rndmendes that's error on what action, or page? Please give more details, or FULL error message, not just one line.

**Comment by rndmendes** [comment]
Hi, just solved the issue. I was missing the reference in the kernel.php.

Thanks for your prompt response.

Regards
